image: archlinux
packages:
  - python-poetry
sources:
  - https://git.sr.ht/~sumner/offlinemsmtp
secrets:
  - 2fb5fd72-fa96-46c6-ab90-6b7cabebba16
tasks:
  - lint: |
      cd offlinemsmtp
      poetry install
      poetry run python setup.py check -mrs
      poetry run flake8
      poetry run mypy offlinemsmtp
      poetry run black --check .

  - build: |
      cd offlinemsmtp
      poetry run python setup.py sdist

  - readme: |
      set +x
      poetry run rst2html5 README.rst | curl -H "Content-Type: text/html"   \
           -H "Authorization: Bearer $(cat ~/.readme-token)"                \
           -XPUT                                                            \
           --data-binary @-                                                 \
           'https://git.sr.ht/api/repos/offlinemsmtp/readme' &&
      echo "README set"
