image: archlinux
packages:
  - git
  - python-poetry
sources:
  - https://git.sr.ht/~sumner/offlinemsmtp
secrets:
  # README Personal Access Token
  - 2fb5fd72-fa96-46c6-ab90-6b7cabebba16
  # PyPi Credentials
  - a935a60f-b0ae-4232-b17e-e6b921ab0b91
environment:
  REPO_NAME: offlinemsmtp
triggers:
  - action: email
    condition: failure
    to: ~sumner/offlinemsmtp-devel@lists.sr.ht
tasks:
  - setup: |
      cd ${REPO_NAME}
      poetry install
      echo "cd ${REPO_NAME}" >> ~/.buildenv

  # If we are on the master branch, compile the README.rst to HTML and set it
  # as the README for the repo.
  - readme: |
      set +x
      git branch --contains | grep master &&
        poetry run rst2html5 README.rst |                           \
          curl -H "Content-Type: text/html"                         \
            -H "Authorization: Bearer $(cat ~/.readme-token)"       \
            -XPUT                                                   \
            --data-binary @-                                        \
            "https://git.sr.ht/api/repos/${REPO_NAME}/readme" &&
        echo "README set"

  - lint: |
      poetry run python setup.py check -mrs
      poetry run flake8
      poetry run mypy offlinemsmtp
      poetry run black --check .

  - build: |
      poetry run python setup.py sdist

#   - deploy: |
#       poetry run twine upload -r testpypi dist/* &&
#       poetry run twine upload dist/*

#   - verify: |
#       pip install offlinemsmtp
