image: archlinux
packages:
  - python-poetry
  - cairo
  - gobject-introspection
sources:
  - https://git.sr.ht/~sumner/offlinemsmtp
secrets:
  # PyPi Credentials
  - a935a60f-b0ae-4232-b17e-e6b921ab0b91
environment:
  REPO_NAME: offlinemsmtp
triggers:
  - action: email
    condition: failure
    to: ~sumner/offlinemsmtp-devel@lists.sr.ht
tasks:
  - setup: |
      cd ${REPO_NAME}
      poetry install
      echo "cd ${REPO_NAME}" >> ~/.buildenv
      echo "source $(poetry env info -p)/bin/activate" >> ~/.buildenv

  - lint: |
      poetry check
      flake8
      mypy offlinemsmtp
      black --check .
      .builds/bin/custom_style_check.py

  - build: |
      poetry build

  - deploy: |
      ./.builds/bin/run_if_tagged_with_version                            \
        "twine upload -r testpypi dist/*"                                 \
        "twine upload dist/*"
