image: archlinux
packages:
  - python-poetry
sources:
  - https://git.sr.ht/~sumner/offlinemsmtp
secrets:
  # PyPi Credentials
  - a935a60f-b0ae-4232-b17e-e6b921ab0b91
environment:
  REPO_NAME: offlinemsmtp
triggers:
  - action: email
    condition: failure
    to: ~sumner/offlinemsmtp-devel@lists.sr.ht
tasks:
  - setup: |
      cd ${REPO_NAME}
      poetry install
      echo "cd ${REPO_NAME}" >> ~/.buildenv

  - lint: |
      poetry run python setup.py check -mrs
      poetry run flake8
      poetry run mypy offlinemsmtp
      poetry run black --check .

  - build: |
      poetry run python setup.py sdist

  - deploy: |
      ./cicd/run_if_tagged_with_version                             \
        "poetry run twine upload -r testpypi dist/*"                \
        "poetry run twine upload dist/*"

  - verify: |
      ./cicd/run_if_tagged_with_version                             \
        "pip install ${REPO_NAME}"
