name: Lint and Build

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: sumnerevans
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Install dependencies
        run: nix-shell --command "poetry install"

      - name: poetry check
        run: nix-shell --command "poetry check"
      - name: flake8
        run: nix-shell --command "poetry run flake8"
      - name: mypy offlinemsmtp
        run: nix-shell --command "poetry run mypy offlinemsmtp"
      - name: black --check .
        run: nix-shell --command "poetry run black --check ."
      - name: custom style check
        run: nix-shell --command "poetry run ./cicd/custom_style_check.py"

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: sumnerevans
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Install dependencies
        run: nix-shell --command "poetry install"

      - name: poetry build
        run: nix-shell --command "poetry build"
